[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- Настройки памяти строго для твоей платы (8 ножек Flash / WROOM-1) ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Автоматическое скачивание библиотеки дисплея
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    adafruit/Adafruit NeoPixel
; Конфигурация компиляции: пробрасываем настройки железа и памяти
build_flags =
    ; Активируем 8 МБ оперативной памяти PSRAM
    -D BOARD_HAS_PSRAM

    -D USER_SETUP_LOADED=1      ; Активируем ручную конфигурацию дисплея
    -D ST7789_2_DRIVER=1        ; Драйвер твоего прямоугольного дисплея ST7789
    -D TFT_WIDTH=240            ; Разрешение экрана
    -D TFT_HEIGHT=320
    -D TFT_RGB_ORDER=TFT_RGB    ; Правильный порядок цветовых каналов
    
    ; --- Твоя родная аппаратная распиновка дисплея ---
    -D TFT_MOSI=7
    -D TFT_SCLK=6
    -D TFT_CS=17
    -D TFT_DC=16
    -D TFT_RST=15
    -D TFT_BL=18
    -D TFT_BACKLIGHT_ON=HIGH
    
    ; --- Скорости шины SPI ---
    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    
    ; --- Аппаратный флаг против циклических ребутов платы ---
    -D USE_HSPI_PORT=1
    
    ; --- Загрузка используемых шрифтов ---
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
